name: Genrate Ascii Art work
on: push

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:

        - name: install cowsay program
          run: sudo apt-get install cowsay -y

        - name: execute cowsay cmd
          run:  cowsay -f dragon "IAm a dragon .....>> dragon.txt" 

        - name: sleep for 30 sec
          run:  sleep 30  
   

    test-job:
        needs: build-job
        runs-on : ubuntu-latest
        steps:
            
            - name: sleep for 10 sec
              run: sleep 10

            - name: test file exists
              run: grep -i "dragon"  dragon.txt

    deploy-job:
        needs: test-job
        runs-on: ubuntu-latest
        steps:
            
            - name: read file
              run: cat dragon.txt

            - name: deploy
              run: echo deploying 
        
 
       
